In [1]:
# ! pip install transformers
import torch
import numpy as np
import matplotlib.pyplot as plt

import torchsummary as summary
from tqdm import tqdm

from torch.utils.data import DataLoader
from torch.nn import CrossEntropyLoss
from torch.optim import Adam
from torch import nn
import torch.nn.functional as F

from sklearn.model_selection import train_test_split
import torch

import pandas as pd
import os
import base64
import gc
import glob, os

from torch.optim import Adam
from tqdm import tqdm

import warnings
warnings.filterwarnings("ignore")

import json
import sys
sys.path.append("..")
from reghub_pack.general_functions import *

C:\Users\hp\miniconda3\envs\tf_gpu\lib\site-packages\scipy\__init__.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 1.20.0)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Using pad_token, but it is not set yet.


In [2]:
# Import data
# Access aws credentials from json file
with open("../aws_credentials.json", 'r') as file:
    aws_creds_json = json.load(file)
# Specify s3 bucket
bucket = "fs-reghub-news-analysis"

# Connect to aws and dowload the files
aws = awsOps(aws_creds_json)
df = aws.get_df(bucket=bucket, file="data_rule_labels_v1.csv")
df_categories = aws.get_df(bucket=bucket, file="rule_labels_v1.csv")

In [3]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df=df[['news_content','rule_labels_comb']]
df = df.reset_index()
del df['index'], df['rule_labels_comb']
# df['target'] = df['news_content']
df

news_content
0      Berenberg Bank analysts have provided a buy ra...
1      The article states that Berenberg, a German in...
2      In their analysis on October 30, 2023, experts...
3      Berenberg Bank has issued a \"buy\" recommenda...
4      The private bank Berenberg has upgraded its ra...
...                                                  ...
14496  INTERVIEW Interview with Les Échos Interview w...
14497  UBS's latest Investor Watch report reveals tha...
14498  SNB erwartet für 2021 Jahresgewinn von rund 26...
14499  0:00 News A cryptocurrency exchange in Hong Ko...
14500  Bloomberg has reported that a number of indivi...

[14501 rows x 1 columns]

In [4]:
# X_train, X_test= train_test_split(df[['news_content','target']], test_size=0.25)
X_train, X_test= train_test_split(df[['news_content']], test_size=0.25)

df_train=X_train
df_val=X_test
df_test=0

In [5]:
df_train=df_train.reset_index()
df_train.drop('index',axis=1,inplace=True)

df_val=df_val.reset_index()
df_val.drop('index',axis=1,inplace=True)

In [6]:
# change datatypes of input data
df_train['news_content']=df_train['news_content'].astype(str)

df_val['news_content']=df_val['news_content'].astype(str)
df_train['news_content'].iloc[0]
train_data=df_train
val_data=df_val

In [7]:
import sys
sys.path.append("..")
# Add the parent directory to the Python path
from reghub_pack.models import LLaMA_RegHub


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
binary_path: C:\Users\hp\miniconda3\envs\tf_gpu\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\hp\miniconda3\envs\tf_gpu\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [8]:
model=LLaMA_RegHub()
# model.display_model_layers()

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [9]:
torch.cuda.empty_cache()
gc.collect()

21

In [10]:
# model.display_model_layers()
import warnings
warnings.filterwarnings("ignore")

In [11]:
model.model_training(train_data=train_data, val_data=val_data)

Asking to pad to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no padding.
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Epoch 1/100:   0%|                                                                           | 0/340 [00:00<?, ?item/s]

tensor([    1,   422,  1050, 29920,  9157,   756,  9326,   393,   967,  7613],
       device='cuda:0')
tensor([    1,   422,  1050, 29920,  9157,   756,  9326,   393,   967,  7613],
       device='cuda:0')
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')


Epoch 1/100:   0%|                                                                           | 0/340 [00:01<?, ?item/s]


Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "C:\Users\hp\miniconda3\envs\tf_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\hp\AppData\Local\Temp\ipykernel_3676\3004462831.py", line 1, in <module>
    model.model_training(train_data=train_data, val_data=val_data)
  File "C:\Users\hp\OneDrive - fs-students.de\FS\Sem 3\CCP\RegHub_news_signal_analysis\3_Modelling\..\reghub_pack\models\LLaMA.py", line 195, in model_training
    output = self(input_ids,labels)
  File "C:\Users\hp\miniconda3\envs\tf_gpu\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\hp\OneDrive - fs-students.de\FS\Sem 3\CCP\RegHub_news_signal_analysis\3_Modelling\..\reghub_pack\models\LLaMA.py", line 62, in forward
    output = self.llama(input_ids= input_ids, attention_mask=attention_mask,return_dict=False)
  File "C:\Users\hp\miniconda3\envs\

In [ ]:
model.val[0]

In [ ]:
a=torch.tensor([[[    1,   450,  4274 ]], [[    1,  1640,   422]],[[    1,  9788, 29892]]])
a

In [ ]:
a.squeeze(1)

In [ ]:
a[:, :-1].contiguous()