In [15]:
import torch

In [16]:
model=torch.load('BERT_mask.pth')

In [17]:
n=0
for x in model.state_dict():
    n=n+1
    print(x)
n

bert.embeddings.word_embeddings.weight
bert.embeddings.position_embeddings.weight
bert.embeddings.token_type_embeddings.weight
bert.embeddings.LayerNorm.weight
bert.embeddings.LayerNorm.bias
bert.encoder.layer.0.attention.self.query.weight
bert.encoder.layer.0.attention.self.query.bias
bert.encoder.layer.0.attention.self.key.weight
bert.encoder.layer.0.attention.self.key.bias
bert.encoder.layer.0.attention.self.value.weight
bert.encoder.layer.0.attention.self.value.bias
bert.encoder.layer.0.attention.output.dense.weight
bert.encoder.layer.0.attention.output.dense.bias
bert.encoder.layer.0.attention.output.LayerNorm.weight
bert.encoder.layer.0.attention.output.LayerNorm.bias
bert.encoder.layer.0.intermediate.dense.weight
bert.encoder.layer.0.intermediate.dense.bias
bert.encoder.layer.0.output.dense.weight
bert.encoder.layer.0.output.dense.bias
bert.encoder.layer.0.output.LayerNorm.weight
bert.encoder.layer.0.output.LayerNorm.bias
bert.encoder.layer.1.attention.self.query.weight
bert.enc

204

In [18]:
model.state_dict()['bert.encoder.layer.11.output.LayerNorm.bias']

tensor([-6.4523e-03, -2.0317e-02,  4.6948e-02,  1.5610e-02, -4.1688e-02,
        -1.3823e-02, -9.9459e-03, -3.1925e-02,  2.5848e-02, -3.5719e-02,
        -6.0546e-02,  3.0363e-02,  1.6680e-02,  1.1848e-02, -3.5969e-03,
        -4.8558e-02,  4.2298e-04, -9.1702e-02,  1.0390e-02,  1.1714e-02,
        -5.8461e-02, -4.7710e-03,  5.0649e-03, -4.4028e-02,  5.0694e-03,
        -3.9832e-02, -4.7910e-02, -5.1699e-02, -9.1433e-02, -4.0506e-02,
        -2.7266e-02, -4.6149e-02, -1.2191e-02, -7.5270e-02, -4.1507e-02,
        -5.7161e-02, -2.7618e-02, -7.8072e-02,  6.9756e-03, -5.9606e-02,
         5.3213e-02, -2.1257e-02, -4.5698e-02, -6.8589e-02, -1.0861e-01,
        -1.8931e-02, -1.3497e-01, -2.3966e-03, -1.0932e-01, -1.1749e-01,
        -2.1131e-02,  4.4923e-02,  3.4135e-02, -2.5268e-02, -8.8217e-02,
        -9.0805e-03, -2.2671e-03, -6.2807e-02, -3.3862e-04, -6.9942e-02,
         4.4014e-02, -8.4269e-02,  2.0889e-02,  5.0521e-02, -4.3462e-02,
        -4.7929e-02, -6.4631e-04, -5.8909e-02,  3.2

In [19]:
from transformers import BertModel
model1 = BertModel.from_pretrained('bert-base-uncased')

In [20]:
model1.state_dict()['encoder.layer.11.output.LayerNorm.bias']

tensor([-6.3461e-03, -1.9894e-02,  4.6285e-02,  1.5851e-02, -4.2569e-02,
        -1.3283e-02, -9.1369e-03, -3.3534e-02,  2.5846e-02, -3.6451e-02,
        -6.1155e-02,  3.0418e-02,  1.7200e-02,  1.2180e-02, -3.3043e-03,
        -4.8502e-02,  5.4115e-04, -9.2394e-02,  1.0380e-02,  1.1926e-02,
        -5.8754e-02, -6.8212e-03,  4.3755e-03, -4.5268e-02,  5.5810e-03,
        -4.1087e-02, -4.8185e-02, -5.1641e-02, -9.1535e-02, -4.0457e-02,
        -2.7150e-02, -4.6665e-02, -1.1590e-02, -7.6277e-02, -4.2056e-02,
        -5.7515e-02, -2.7733e-02, -7.7364e-02,  6.9931e-03, -5.9466e-02,
         5.3589e-02, -2.0961e-02, -4.5835e-02, -6.9220e-02, -1.0842e-01,
        -1.9135e-02, -1.3539e-01, -1.7333e-03, -1.0963e-01, -1.1798e-01,
        -2.1245e-02,  4.4968e-02,  3.4347e-02, -2.5082e-02, -8.8453e-02,
        -8.9132e-03, -2.2133e-03, -6.2073e-02, -5.2548e-04, -6.9640e-02,
         4.3890e-02, -8.3953e-02,  2.0464e-02,  5.0537e-02, -4.3895e-02,
        -4.7470e-02, -9.3629e-04, -5.9144e-02,  3.3

In [21]:
for x in model1.state_dict()['encoder.layer.11.output.LayerNorm.bias']:
    print(x)

tensor(-0.0063)
tensor(-0.0199)
tensor(0.0463)
tensor(0.0159)
tensor(-0.0426)
tensor(-0.0133)
tensor(-0.0091)
tensor(-0.0335)
tensor(0.0258)
tensor(-0.0365)
tensor(-0.0612)
tensor(0.0304)
tensor(0.0172)
tensor(0.0122)
tensor(-0.0033)
tensor(-0.0485)
tensor(0.0005)
tensor(-0.0924)
tensor(0.0104)
tensor(0.0119)
tensor(-0.0588)
tensor(-0.0068)
tensor(0.0044)
tensor(-0.0453)
tensor(0.0056)
tensor(-0.0411)
tensor(-0.0482)
tensor(-0.0516)
tensor(-0.0915)
tensor(-0.0405)
tensor(-0.0271)
tensor(-0.0467)
tensor(-0.0116)
tensor(-0.0763)
tensor(-0.0421)
tensor(-0.0575)
tensor(-0.0277)
tensor(-0.0774)
tensor(0.0070)
tensor(-0.0595)
tensor(0.0536)
tensor(-0.0210)
tensor(-0.0458)
tensor(-0.0692)
tensor(-0.1084)
tensor(-0.0191)
tensor(-0.1354)
tensor(-0.0017)
tensor(-0.1096)
tensor(-0.1180)
tensor(-0.0212)
tensor(0.0450)
tensor(0.0343)
tensor(-0.0251)
tensor(-0.0885)
tensor(-0.0089)
tensor(-0.0022)
tensor(-0.0621)
tensor(-0.0005)
tensor(-0.0696)
tensor(0.0439)
tensor(-0.0840)
tensor(0.0205)
tensor(0.

In [22]:
state_dict = model.state_dict()

In [23]:
keys_to_delete = ['cls.predictions.decoder.bias']  # Example keys
for key in keys_to_delete:
    if key in state_dict:
        del state_dict[key]


In [24]:
n=0
a=[]
for x in state_dict:
    n=n+1
    print(x)
    a.append(str(x))
    
n
a

bert.embeddings.word_embeddings.weight
bert.embeddings.position_embeddings.weight
bert.embeddings.token_type_embeddings.weight
bert.embeddings.LayerNorm.weight
bert.embeddings.LayerNorm.bias
bert.encoder.layer.0.attention.self.query.weight
bert.encoder.layer.0.attention.self.query.bias
bert.encoder.layer.0.attention.self.key.weight
bert.encoder.layer.0.attention.self.key.bias
bert.encoder.layer.0.attention.self.value.weight
bert.encoder.layer.0.attention.self.value.bias
bert.encoder.layer.0.attention.output.dense.weight
bert.encoder.layer.0.attention.output.dense.bias
bert.encoder.layer.0.attention.output.LayerNorm.weight
bert.encoder.layer.0.attention.output.LayerNorm.bias
bert.encoder.layer.0.intermediate.dense.weight
bert.encoder.layer.0.intermediate.dense.bias
bert.encoder.layer.0.output.dense.weight
bert.encoder.layer.0.output.dense.bias
bert.encoder.layer.0.output.LayerNorm.weight
bert.encoder.layer.0.output.LayerNorm.bias
bert.encoder.layer.1.attention.self.query.weight
bert.enc

['bert.embeddings.word_embeddings.weight',
 'bert.embeddings.position_embeddings.weight',
 'bert.embeddings.token_type_embeddings.weight',
 'bert.embeddings.LayerNorm.weight',
 'bert.embeddings.LayerNorm.bias',
 'bert.encoder.layer.0.attention.self.query.weight',
 'bert.encoder.layer.0.attention.self.query.bias',
 'bert.encoder.layer.0.attention.self.key.weight',
 'bert.encoder.layer.0.attention.self.key.bias',
 'bert.encoder.layer.0.attention.self.value.weight',
 'bert.encoder.layer.0.attention.self.value.bias',
 'bert.encoder.layer.0.attention.output.dense.weight',
 'bert.encoder.layer.0.attention.output.dense.bias',
 'bert.encoder.layer.0.attention.output.LayerNorm.weight',
 'bert.encoder.layer.0.attention.output.LayerNorm.bias',
 'bert.encoder.layer.0.intermediate.dense.weight',
 'bert.encoder.layer.0.intermediate.dense.bias',
 'bert.encoder.layer.0.output.dense.weight',
 'bert.encoder.layer.0.output.dense.bias',
 'bert.encoder.layer.0.output.LayerNorm.weight',
 'bert.encoder.layer

In [25]:
def transfer_weights(model1,model2):
    
    #retrieve the layers
    n1=0
    del_layers=[]
    for x in model1.state_dict():
        n1=n1+1
        if n1>197:
            del_layers.append(str(x))
           
    # delete the lyers
    state_dict = model1.state_dict()
    for key in del_layers:
        if key in state_dict:
            del state_dict[key]
    
    # transfer weights
    for x, y in zip(state_dict,model2.state_dict()):
        for n in range(len(model2.state_dict()[str(y)])):
            model2.state_dict()[str(y)][n] = state_dict[str(x)][n]
            
    return model2

transfer_weights(model,model1)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

In [26]:
model3 = transfer_weights(model,model1)

In [28]:
model3.state_dict()['encoder.layer.11.output.LayerNorm.bias']

tensor([-6.4523e-03, -2.0317e-02,  4.6948e-02,  1.5610e-02, -4.1688e-02,
        -1.3823e-02, -9.9459e-03, -3.1925e-02,  2.5848e-02, -3.5719e-02,
        -6.0546e-02,  3.0363e-02,  1.6680e-02,  1.1848e-02, -3.5969e-03,
        -4.8558e-02,  4.2298e-04, -9.1702e-02,  1.0390e-02,  1.1714e-02,
        -5.8461e-02, -4.7710e-03,  5.0649e-03, -4.4028e-02,  5.0694e-03,
        -3.9832e-02, -4.7910e-02, -5.1699e-02, -9.1433e-02, -4.0506e-02,
        -2.7266e-02, -4.6149e-02, -1.2191e-02, -7.5270e-02, -4.1507e-02,
        -5.7161e-02, -2.7618e-02, -7.8072e-02,  6.9756e-03, -5.9606e-02,
         5.3213e-02, -2.1257e-02, -4.5698e-02, -6.8589e-02, -1.0861e-01,
        -1.8931e-02, -1.3497e-01, -2.3966e-03, -1.0932e-01, -1.1749e-01,
        -2.1131e-02,  4.4923e-02,  3.4135e-02, -2.5268e-02, -8.8217e-02,
        -9.0805e-03, -2.2671e-03, -6.2807e-02, -3.3862e-04, -6.9942e-02,
         4.4014e-02, -8.4269e-02,  2.0889e-02,  5.0521e-02, -4.3462e-02,
        -4.7929e-02, -6.4631e-04, -5.8909e-02,  3.2

In [29]:
torch.save(model3, 'BERT_comparison.pth')